import type { Deal } from './models';

export const MOCK_DEALS: Deal[] = [
  {
    productId: 'mock-001',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    series: 'The Kingkiller Chronicle #1',
    url: 'https://www.kobo.com/be/en/ebook/the-name-of-the-wind',
    coverUrl: 'https://picsum.photos/seed/mock-001/300/450',
    language: 'en',
    source: 'wishlist',
    priceEur: 4.99,
    wasPriceEur: 12.99,
    discountPercent: 62,
    isFree: false,
    isNew: true,
    isPriceDrop: false,
    isOwned: false,
    firstSeen: '2026-08-10T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-002',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    series: '',
    url: 'https://www.kobo.com/be/en/ebook/project-hail-mary',
    coverUrl: 'https://picsum.photos/seed/mock-002/300/450',
    language: 'en',
    source: 'bestdeals',
    priceEur: 5.49,
    wasPriceEur: 14.99,
    discountPercent: 63,
    isFree: false,
    isNew: false,
    isPriceDrop: true,
    isOwned: false,
    firstSeen: '2026-08-05T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-003',
    title: 'Dune',
    author: 'Frank Herbert',
    series: 'Dune #1',
    url: 'https://www.kobo.com/be/en/ebook/dune',
    coverUrl: 'https://picsum.photos/seed/mock-003/300/450',
    language: 'en',
    source: 'wishlist',
    priceEur: 0,
    wasPriceEur: 9.99,
    discountPercent: 100,
    isFree: true,
    isNew: false,
    isPriceDrop: false,
    isOwned: true,
    firstSeen: '2026-07-20T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-004',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    series: 'Middle-earth #1',
    url: 'https://www.kobo.com/be/en/ebook/the-hobbit',
    coverUrl: 'https://picsum.photos/seed/mock-004/300/450',
    language: 'en',
    source: 'bestdeals',
    priceEur: 3.99,
    wasPriceEur: 8.99,
    discountPercent: 56,
    isFree: false,
    isNew: true,
    isPriceDrop: false,
    isOwned: false,
    firstSeen: '2026-08-12T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-005',
    title: '1984',
    author: 'George Orwell',
    series: '',
    url: 'https://www.kobo.com/be/en/ebook/1984',
    coverUrl: 'https://picsum.photos/seed/mock-005/300/450',
    language: 'en',
    source: 'wishlist',
    priceEur: 2.99,
    wasPriceEur: 7.99,
    discountPercent: 63,
    isFree: false,
    isNew: false,
    isPriceDrop: true,
    isOwned: false,
    firstSeen: '2026-07-15T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-006',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    series: '',
    url: 'https://www.kobo.com/be/en/ebook/brave-new-world',
    coverUrl: 'https://picsum.photos/seed/mock-006/300/450',
    language: 'en',
    source: 'bestdeals',
    priceEur: 1.99,
    wasPriceEur: 6.99,
    discountPercent: 72,
    isFree: false,
    isNew: false,
    isPriceDrop: false,
    isOwned: true,
    firstSeen: '2026-06-01T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-007',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    series: '',
    url: 'https://www.kobo.com/be/en/ebook/the-great-gatsby',
    coverUrl: 'https://picsum.photos/seed/mock-007/300/450',
    language: 'en',
    source: 'wishlist',
    priceEur: 0,
    wasPriceEur: 5.99,
    discountPercent: 100,
    isFree: true,
    isNew: false,
    isPriceDrop: false,
    isOwned: false,
    firstSeen: '2026-08-01T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-008',
    title: 'Le Petit Prince',
    author: 'Antoine de Saint-Exupéry',
    series: '',
    url: 'https://www.kobo.com/be/en/ebook/le-petit-prince',
    coverUrl: 'https://picsum.photos/seed/mock-008/300/450',
    language: 'fr',
    source: 'bestdeals',
    priceEur: 3.49,
    wasPriceEur: 9.99,
    discountPercent: 65,
    isFree: false,
    isNew: true,
    isPriceDrop: false,
    isOwned: false,
    firstSeen: '2026-08-11T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-009',
    title: 'Harry Potter and the Philosopher\'s Stone',
    author: 'J.K. Rowling',
    series: 'Harry Potter #1',
    url: 'https://www.kobo.com/be/en/ebook/harry-potter-and-the-philosopher-s-stone',
    coverUrl: 'https://picsum.photos/seed/mock-009/300/450',
    language: 'en',
    source: 'wishlist',
    priceEur: 6.99,
    wasPriceEur: 12.99,
    discountPercent: 46,
    isFree: false,
    isNew: false,
    isPriceDrop: true,
    isOwned: true,
    firstSeen: '2026-05-10T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-010',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    series: '',
    url: 'https://www.kobo.com/be/en/ebook/the-alchemist',
    coverUrl: 'https://picsum.photos/seed/mock-010/300/450',
    language: 'en',
    source: 'bestdeals',
    priceEur: 4.49,
    wasPriceEur: 11.99,
    discountPercent: 63,
    isFree: false,
    isNew: false,
    isPriceDrop: false,
    isOwned: false,
    firstSeen: '2026-07-25T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-011',
    title: 'The Hitchhiker\'s Guide to the Galaxy',
    author: 'Douglas Adams',
    series: 'Hitchhiker\'s Guide #1',
    url: 'https://www.kobo.com/be/en/ebook/the-hitchhiker-s-guide-to-the-galaxy',
    coverUrl: 'https://picsum.photos/seed/mock-011/300/450',
    language: 'en',
    source: 'wishlist',
    priceEur: 2.49,
    wasPriceEur: 8.99,
    discountPercent: 72,
    isFree: false,
    isNew: true,
    isPriceDrop: false,
    isOwned: false,
    firstSeen: '2026-08-10T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
  {
    productId: 'mock-012',
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    series: '',
    url: 'https://www.kobo.com/be/en/ebook/fahrenheit-451',
    coverUrl: 'https://picsum.photos/seed/mock-012/300/450',
    language: 'en',
    source: 'bestdeals',
    priceEur: 1.99,
    wasPriceEur: 7.49,
    discountPercent: 73,
    isFree: false,
    isNew: false,
    isPriceDrop: true,
    isOwned: false,
    firstSeen: '2026-06-15T10:00:00Z',
    lastSeen: '2026-08-13T10:00:00Z',
    runId: 1,
  },
];
